/*
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.containerregistry.api;

import com.ionoscloud.containerregistry.ApiCallback;
import com.ionoscloud.containerregistry.ApiClient;
import com.ionoscloud.containerregistry.ApiException;
import com.ionoscloud.containerregistry.ApiResponse;
import com.ionoscloud.containerregistry.Configuration;
import com.ionoscloud.containerregistry.Pair;
import com.ionoscloud.containerregistry.ProgressRequestBody;
import com.ionoscloud.containerregistry.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.ionoscloud.containerregistry.model.Error;
import com.ionoscloud.containerregistry.model.VulnerabilityRead;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class VulnerabilitiesApi {
    private ApiClient localVarApiClient;

    public VulnerabilitiesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public VulnerabilitiesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    /**
     * Build call for vulnerabilitiesFindByID
     * @param vulnerabilityId The ID of the Vulnerability that should be retrieved. (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Getting Vulnerability was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call vulnerabilitiesFindByIDCall(String vulnerabilityId, final ApiCallback<VulnerabilityRead> _callback) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/vulnerabilities/{vulnerabilityId}"
            .replaceAll("\\{" + "vulnerabilityId" + "\\}", localVarApiClient.escapeString(vulnerabilityId.toString()));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        String[] localVarAuthNames = new String[] { "tokenAuth" };
        return localVarApiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call vulnerabilitiesFindByIDValidateBeforeCall(String vulnerabilityId, final ApiCallback<VulnerabilityRead> _callback) throws ApiException {
        
        // verify the required parameter 'vulnerabilityId' is set
        if (vulnerabilityId == null) {
            throw new ApiException("Missing the required parameter 'vulnerabilityId' when calling vulnerabilitiesFindByID(Async)");
        }
        

        okhttp3.Call localVarCall = vulnerabilitiesFindByIDCall(vulnerabilityId, _callback);
        return localVarCall;

    }

    /**
     * Retrieve Vulnerability
     * Returns the Vulnerability by ID.
     * @param vulnerabilityId The ID of the Vulnerability that should be retrieved. (required)
     * @return VulnerabilityRead
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Getting Vulnerability was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public VulnerabilityRead vulnerabilitiesFindByID(String vulnerabilityId) throws ApiException {
        ApiResponse<VulnerabilityRead> localVarResp = vulnerabilitiesFindByIDWithHttpInfo(vulnerabilityId);
        return localVarResp.getData();
    }

    /**
     * Retrieve Vulnerability
     * Returns the Vulnerability by ID.
     * @param vulnerabilityId The ID of the Vulnerability that should be retrieved. (required)
     * @return ApiResponse&lt;VulnerabilityRead&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Getting Vulnerability was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<VulnerabilityRead> vulnerabilitiesFindByIDWithHttpInfo(String vulnerabilityId) throws ApiException {
        okhttp3.Call localVarCall = vulnerabilitiesFindByIDValidateBeforeCall(vulnerabilityId, null);
        Type localVarReturnType = new TypeToken<VulnerabilityRead>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Retrieve Vulnerability (asynchronously)
     * Returns the Vulnerability by ID.
     * @param vulnerabilityId The ID of the Vulnerability that should be retrieved. (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Getting Vulnerability was successful. </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> ### Bad Request The request send to the API was malformed.  </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> ### Unauthorized The request is missing authorization information or the authorization information provided are expired.  </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> ### Not Found The resource that was requested could not be found.  </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> ### Internal Server Error An internal error occurred. We apologize for the inconvenience!  </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call vulnerabilitiesFindByIDAsync(String vulnerabilityId, final ApiCallback<VulnerabilityRead> _callback) throws ApiException {

        okhttp3.Call localVarCall = vulnerabilitiesFindByIDValidateBeforeCall(vulnerabilityId, _callback);
        Type localVarReturnType = new TypeToken<VulnerabilityRead>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
