/*
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.containerregistry.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.containerregistry.model.ArtifactMetadataAllOf;
import com.ionoscloud.containerregistry.model.Metadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ArtifactMetadata
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-15T14:36:52.394811Z[Etc/UTC]")

public class ArtifactMetadata {
  
  public static final String SERIALIZED_NAME_CREATED_DATE = "createdDate";
  @SerializedName(SERIALIZED_NAME_CREATED_DATE)
  private OffsetDateTime createdDate;


  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private String createdBy;


  public static final String SERIALIZED_NAME_CREATED_BY_USER_ID = "createdByUserId";
  @SerializedName(SERIALIZED_NAME_CREATED_BY_USER_ID)
  private String createdByUserId;


  public static final String SERIALIZED_NAME_LAST_MODIFIED_DATE = "lastModifiedDate";
  @SerializedName(SERIALIZED_NAME_LAST_MODIFIED_DATE)
  private OffsetDateTime lastModifiedDate;


  public static final String SERIALIZED_NAME_LAST_MODIFIED_BY = "lastModifiedBy";
  @SerializedName(SERIALIZED_NAME_LAST_MODIFIED_BY)
  private String lastModifiedBy;


  public static final String SERIALIZED_NAME_LAST_MODIFIED_BY_USER_ID = "lastModifiedByUserId";
  @SerializedName(SERIALIZED_NAME_LAST_MODIFIED_BY_USER_ID)
  private String lastModifiedByUserId;


  public static final String SERIALIZED_NAME_RESOURCE_U_R_N = "resourceURN";
  @SerializedName(SERIALIZED_NAME_RESOURCE_U_R_N)
  private String resourceURN;


  public static final String SERIALIZED_NAME_LAST_PUSHED_AT = "lastPushedAt";
  @SerializedName(SERIALIZED_NAME_LAST_PUSHED_AT)
  private OffsetDateTime lastPushedAt;


  public static final String SERIALIZED_NAME_LAST_PULLED_AT = "lastPulledAt";
  @SerializedName(SERIALIZED_NAME_LAST_PULLED_AT)
  private OffsetDateTime lastPulledAt;


  public static final String SERIALIZED_NAME_LAST_SCANNED_AT = "lastScannedAt";
  @SerializedName(SERIALIZED_NAME_LAST_SCANNED_AT)
  private OffsetDateTime lastScannedAt;


  public static final String SERIALIZED_NAME_PUSH_COUNT = "pushCount";
  @SerializedName(SERIALIZED_NAME_PUSH_COUNT)
  private Long pushCount;


  public static final String SERIALIZED_NAME_PULL_COUNT = "pullCount";
  @SerializedName(SERIALIZED_NAME_PULL_COUNT)
  private Long pullCount;


  public static final String SERIALIZED_NAME_VULN_MAX_SEVERITY = "vulnMaxSeverity";
  @SerializedName(SERIALIZED_NAME_VULN_MAX_SEVERITY)
  private String vulnMaxSeverity;


  public static final String SERIALIZED_NAME_VULN_TOTAL_SCORE = "vulnTotalScore";
  @SerializedName(SERIALIZED_NAME_VULN_TOTAL_SCORE)
  private Float vulnTotalScore;


  public static final String SERIALIZED_NAME_VULN_TOTAL_COUNT = "vulnTotalCount";
  @SerializedName(SERIALIZED_NAME_VULN_TOTAL_COUNT)
  private Long vulnTotalCount;


  public static final String SERIALIZED_NAME_VULN_FIXABLE_COUNT = "vulnFixableCount";
  @SerializedName(SERIALIZED_NAME_VULN_FIXABLE_COUNT)
  private Long vulnFixableCount;

  

  public ArtifactMetadata createdDate(OffsetDateTime createdDate) {
    
    this.createdDate = createdDate;
    return this;
  }

   /**
   * The ISO 8601 creation timestamp.
   * @return createdDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-12-10T13:37:50+01:00", value = "The ISO 8601 creation timestamp.")

  public OffsetDateTime getCreatedDate() {
    return createdDate;
  }


  public void setCreatedDate(OffsetDateTime createdDate) {
    this.createdDate = createdDate;
  }



  public ArtifactMetadata createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Unique name of the identity that created the resource.
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ionos:identity:::users/87f9a82e-b28d-49ed-9d04-fba2c0459cd3", value = "Unique name of the identity that created the resource.")

  public String getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }



  public ArtifactMetadata createdByUserId(String createdByUserId) {
    
    this.createdByUserId = createdByUserId;
    return this;
  }

   /**
   * Get createdByUserId
   * @return createdByUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "87f9a82e-b28d-49ed-9d04-fba2c0459cd3", value = "")

  public String getCreatedByUserId() {
    return createdByUserId;
  }


  public void setCreatedByUserId(String createdByUserId) {
    this.createdByUserId = createdByUserId;
  }



  public ArtifactMetadata lastModifiedDate(OffsetDateTime lastModifiedDate) {
    
    this.lastModifiedDate = lastModifiedDate;
    return this;
  }

   /**
   * The ISO 8601 modified timestamp.
   * @return lastModifiedDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2020-12-11T13:37:50+01:00", value = "The ISO 8601 modified timestamp.")

  public OffsetDateTime getLastModifiedDate() {
    return lastModifiedDate;
  }


  public void setLastModifiedDate(OffsetDateTime lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
  }



  public ArtifactMetadata lastModifiedBy(String lastModifiedBy) {
    
    this.lastModifiedBy = lastModifiedBy;
    return this;
  }

   /**
   * Unique name of the identity that last modified the resource.
   * @return lastModifiedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ionos:identity:::users/87f9a82e-b28d-49ed-9d04-fba2c0459cd3", value = "Unique name of the identity that last modified the resource.")

  public String getLastModifiedBy() {
    return lastModifiedBy;
  }


  public void setLastModifiedBy(String lastModifiedBy) {
    this.lastModifiedBy = lastModifiedBy;
  }



  public ArtifactMetadata lastModifiedByUserId(String lastModifiedByUserId) {
    
    this.lastModifiedByUserId = lastModifiedByUserId;
    return this;
  }

   /**
   * Get lastModifiedByUserId
   * @return lastModifiedByUserId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "87f9a82e-b28d-49ed-9d04-fba2c0459cd3", value = "")

  public String getLastModifiedByUserId() {
    return lastModifiedByUserId;
  }


  public void setLastModifiedByUserId(String lastModifiedByUserId) {
    this.lastModifiedByUserId = lastModifiedByUserId;
  }



  public ArtifactMetadata resourceURN(String resourceURN) {
    
    this.resourceURN = resourceURN;
    return this;
  }

   /**
   * Unique name of the resource.
   * @return resourceURN
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ionos:<product>:<location>:<contract>:<resource-path>", value = "Unique name of the resource.")

  public String getResourceURN() {
    return resourceURN;
  }


  public void setResourceURN(String resourceURN) {
    this.resourceURN = resourceURN;
  }



  public ArtifactMetadata lastPushedAt(OffsetDateTime lastPushedAt) {
    
    this.lastPushedAt = lastPushedAt;
    return this;
  }

   /**
   * The date and time the artifact was last pushed
   * @return lastPushedAt
  **/
  @ApiModelProperty(required = true, value = "The date and time the artifact was last pushed")

  public OffsetDateTime getLastPushedAt() {
    return lastPushedAt;
  }


  public void setLastPushedAt(OffsetDateTime lastPushedAt) {
    this.lastPushedAt = lastPushedAt;
  }



  public ArtifactMetadata lastPulledAt(OffsetDateTime lastPulledAt) {
    
    this.lastPulledAt = lastPulledAt;
    return this;
  }

   /**
   * The date and time the artifact was last pulled
   * @return lastPulledAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time the artifact was last pulled")

  public OffsetDateTime getLastPulledAt() {
    return lastPulledAt;
  }


  public void setLastPulledAt(OffsetDateTime lastPulledAt) {
    this.lastPulledAt = lastPulledAt;
  }



  public ArtifactMetadata lastScannedAt(OffsetDateTime lastScannedAt) {
    
    this.lastScannedAt = lastScannedAt;
    return this;
  }

   /**
   * The date and time the artifact was last scanned
   * @return lastScannedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time the artifact was last scanned")

  public OffsetDateTime getLastScannedAt() {
    return lastScannedAt;
  }


  public void setLastScannedAt(OffsetDateTime lastScannedAt) {
    this.lastScannedAt = lastScannedAt;
  }



  public ArtifactMetadata pushCount(Long pushCount) {
    
    this.pushCount = pushCount;
    return this;
  }

   /**
   * The number of times the artifact was pushed
   * @return pushCount
  **/
  @ApiModelProperty(example = "1", required = true, value = "The number of times the artifact was pushed")

  public Long getPushCount() {
    return pushCount;
  }


  public void setPushCount(Long pushCount) {
    this.pushCount = pushCount;
  }



  public ArtifactMetadata pullCount(Long pullCount) {
    
    this.pullCount = pullCount;
    return this;
  }

   /**
   * The number of times the artifact was pulled
   * @return pullCount
  **/
  @ApiModelProperty(example = "42", required = true, value = "The number of times the artifact was pulled")

  public Long getPullCount() {
    return pullCount;
  }


  public void setPullCount(Long pullCount) {
    this.pullCount = pullCount;
  }



  public ArtifactMetadata vulnMaxSeverity(String vulnMaxSeverity) {
    
    this.vulnMaxSeverity = vulnMaxSeverity;
    return this;
  }

   /**
   * The maximum vulnerability severity of the artifact, if any
   * @return vulnMaxSeverity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The maximum vulnerability severity of the artifact, if any")

  public String getVulnMaxSeverity() {
    return vulnMaxSeverity;
  }


  public void setVulnMaxSeverity(String vulnMaxSeverity) {
    this.vulnMaxSeverity = vulnMaxSeverity;
  }



  public ArtifactMetadata vulnTotalScore(Float vulnTotalScore) {
    
    this.vulnTotalScore = vulnTotalScore;
    return this;
  }

   /**
   * The total CVSS score of all vulnerabilities of the artifact
   * @return vulnTotalScore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "9.8", value = "The total CVSS score of all vulnerabilities of the artifact")

  public Float getVulnTotalScore() {
    return vulnTotalScore;
  }


  public void setVulnTotalScore(Float vulnTotalScore) {
    this.vulnTotalScore = vulnTotalScore;
  }



  public ArtifactMetadata vulnTotalCount(Long vulnTotalCount) {
    
    this.vulnTotalCount = vulnTotalCount;
    return this;
  }

   /**
   * The total number of vulnerabilities of the artifact
   * @return vulnTotalCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "20", value = "The total number of vulnerabilities of the artifact")

  public Long getVulnTotalCount() {
    return vulnTotalCount;
  }


  public void setVulnTotalCount(Long vulnTotalCount) {
    this.vulnTotalCount = vulnTotalCount;
  }



  public ArtifactMetadata vulnFixableCount(Long vulnFixableCount) {
    
    this.vulnFixableCount = vulnFixableCount;
    return this;
  }

   /**
   * The number of fixable vulnerabilities of the artifact
   * @return vulnFixableCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "The number of fixable vulnerabilities of the artifact")

  public Long getVulnFixableCount() {
    return vulnFixableCount;
  }


  public void setVulnFixableCount(Long vulnFixableCount) {
    this.vulnFixableCount = vulnFixableCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArtifactMetadata artifactMetadata = (ArtifactMetadata) o;
    return Objects.equals(this.createdDate, artifactMetadata.createdDate) && Objects.equals(this.createdBy, artifactMetadata.createdBy) && Objects.equals(this.createdByUserId, artifactMetadata.createdByUserId) && Objects.equals(this.lastModifiedDate, artifactMetadata.lastModifiedDate) && Objects.equals(this.lastModifiedBy, artifactMetadata.lastModifiedBy) && Objects.equals(this.lastModifiedByUserId, artifactMetadata.lastModifiedByUserId) && Objects.equals(this.resourceURN, artifactMetadata.resourceURN) && Objects.equals(this.lastPushedAt, artifactMetadata.lastPushedAt) && Objects.equals(this.lastPulledAt, artifactMetadata.lastPulledAt) && Objects.equals(this.lastScannedAt, artifactMetadata.lastScannedAt) && Objects.equals(this.pushCount, artifactMetadata.pushCount) && Objects.equals(this.pullCount, artifactMetadata.pullCount) && Objects.equals(this.vulnMaxSeverity, artifactMetadata.vulnMaxSeverity) && Objects.equals(this.vulnTotalScore, artifactMetadata.vulnTotalScore) && Objects.equals(this.vulnTotalCount, artifactMetadata.vulnTotalCount) && Objects.equals(this.vulnFixableCount, artifactMetadata.vulnFixableCount);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArtifactMetadata {\n");
    
    sb.append("    createdDate: ").append(toIndentedString(createdDate)).append("\n");

    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");

    sb.append("    createdByUserId: ").append(toIndentedString(createdByUserId)).append("\n");

    sb.append("    lastModifiedDate: ").append(toIndentedString(lastModifiedDate)).append("\n");

    sb.append("    lastModifiedBy: ").append(toIndentedString(lastModifiedBy)).append("\n");

    sb.append("    lastModifiedByUserId: ").append(toIndentedString(lastModifiedByUserId)).append("\n");

    sb.append("    resourceURN: ").append(toIndentedString(resourceURN)).append("\n");

    sb.append("    lastPushedAt: ").append(toIndentedString(lastPushedAt)).append("\n");

    sb.append("    lastPulledAt: ").append(toIndentedString(lastPulledAt)).append("\n");

    sb.append("    lastScannedAt: ").append(toIndentedString(lastScannedAt)).append("\n");

    sb.append("    pushCount: ").append(toIndentedString(pushCount)).append("\n");

    sb.append("    pullCount: ").append(toIndentedString(pullCount)).append("\n");

    sb.append("    vulnMaxSeverity: ").append(toIndentedString(vulnMaxSeverity)).append("\n");

    sb.append("    vulnTotalScore: ").append(toIndentedString(vulnTotalScore)).append("\n");

    sb.append("    vulnTotalCount: ").append(toIndentedString(vulnTotalCount)).append("\n");

    sb.append("    vulnFixableCount: ").append(toIndentedString(vulnFixableCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

