/*
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.containerregistry.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * ArtifactMetadataAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-15T14:36:52.394811Z[Etc/UTC]")

public class ArtifactMetadataAllOf {
  
  public static final String SERIALIZED_NAME_LAST_PUSHED_AT = "lastPushedAt";
  @SerializedName(SERIALIZED_NAME_LAST_PUSHED_AT)
  private OffsetDateTime lastPushedAt;


  public static final String SERIALIZED_NAME_LAST_PULLED_AT = "lastPulledAt";
  @SerializedName(SERIALIZED_NAME_LAST_PULLED_AT)
  private OffsetDateTime lastPulledAt;


  public static final String SERIALIZED_NAME_LAST_SCANNED_AT = "lastScannedAt";
  @SerializedName(SERIALIZED_NAME_LAST_SCANNED_AT)
  private OffsetDateTime lastScannedAt;


  public static final String SERIALIZED_NAME_PUSH_COUNT = "pushCount";
  @SerializedName(SERIALIZED_NAME_PUSH_COUNT)
  private Long pushCount;


  public static final String SERIALIZED_NAME_PULL_COUNT = "pullCount";
  @SerializedName(SERIALIZED_NAME_PULL_COUNT)
  private Long pullCount;


  public static final String SERIALIZED_NAME_VULN_MAX_SEVERITY = "vulnMaxSeverity";
  @SerializedName(SERIALIZED_NAME_VULN_MAX_SEVERITY)
  private String vulnMaxSeverity;


  public static final String SERIALIZED_NAME_VULN_TOTAL_SCORE = "vulnTotalScore";
  @SerializedName(SERIALIZED_NAME_VULN_TOTAL_SCORE)
  private Float vulnTotalScore;


  public static final String SERIALIZED_NAME_VULN_TOTAL_COUNT = "vulnTotalCount";
  @SerializedName(SERIALIZED_NAME_VULN_TOTAL_COUNT)
  private Long vulnTotalCount;


  public static final String SERIALIZED_NAME_VULN_FIXABLE_COUNT = "vulnFixableCount";
  @SerializedName(SERIALIZED_NAME_VULN_FIXABLE_COUNT)
  private Long vulnFixableCount;

  

  public ArtifactMetadataAllOf lastPushedAt(OffsetDateTime lastPushedAt) {
    
    this.lastPushedAt = lastPushedAt;
    return this;
  }

   /**
   * The date and time the artifact was last pushed
   * @return lastPushedAt
  **/
  @ApiModelProperty(required = true, value = "The date and time the artifact was last pushed")

  public OffsetDateTime getLastPushedAt() {
    return lastPushedAt;
  }


  public void setLastPushedAt(OffsetDateTime lastPushedAt) {
    this.lastPushedAt = lastPushedAt;
  }



  public ArtifactMetadataAllOf lastPulledAt(OffsetDateTime lastPulledAt) {
    
    this.lastPulledAt = lastPulledAt;
    return this;
  }

   /**
   * The date and time the artifact was last pulled
   * @return lastPulledAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time the artifact was last pulled")

  public OffsetDateTime getLastPulledAt() {
    return lastPulledAt;
  }


  public void setLastPulledAt(OffsetDateTime lastPulledAt) {
    this.lastPulledAt = lastPulledAt;
  }



  public ArtifactMetadataAllOf lastScannedAt(OffsetDateTime lastScannedAt) {
    
    this.lastScannedAt = lastScannedAt;
    return this;
  }

   /**
   * The date and time the artifact was last scanned
   * @return lastScannedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date and time the artifact was last scanned")

  public OffsetDateTime getLastScannedAt() {
    return lastScannedAt;
  }


  public void setLastScannedAt(OffsetDateTime lastScannedAt) {
    this.lastScannedAt = lastScannedAt;
  }



  public ArtifactMetadataAllOf pushCount(Long pushCount) {
    
    this.pushCount = pushCount;
    return this;
  }

   /**
   * The number of times the artifact was pushed
   * @return pushCount
  **/
  @ApiModelProperty(example = "1", required = true, value = "The number of times the artifact was pushed")

  public Long getPushCount() {
    return pushCount;
  }


  public void setPushCount(Long pushCount) {
    this.pushCount = pushCount;
  }



  public ArtifactMetadataAllOf pullCount(Long pullCount) {
    
    this.pullCount = pullCount;
    return this;
  }

   /**
   * The number of times the artifact was pulled
   * @return pullCount
  **/
  @ApiModelProperty(example = "42", required = true, value = "The number of times the artifact was pulled")

  public Long getPullCount() {
    return pullCount;
  }


  public void setPullCount(Long pullCount) {
    this.pullCount = pullCount;
  }



  public ArtifactMetadataAllOf vulnMaxSeverity(String vulnMaxSeverity) {
    
    this.vulnMaxSeverity = vulnMaxSeverity;
    return this;
  }

   /**
   * The maximum vulnerability severity of the artifact, if any
   * @return vulnMaxSeverity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The maximum vulnerability severity of the artifact, if any")

  public String getVulnMaxSeverity() {
    return vulnMaxSeverity;
  }


  public void setVulnMaxSeverity(String vulnMaxSeverity) {
    this.vulnMaxSeverity = vulnMaxSeverity;
  }



  public ArtifactMetadataAllOf vulnTotalScore(Float vulnTotalScore) {
    
    this.vulnTotalScore = vulnTotalScore;
    return this;
  }

   /**
   * The total CVSS score of all vulnerabilities of the artifact
   * @return vulnTotalScore
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "9.8", value = "The total CVSS score of all vulnerabilities of the artifact")

  public Float getVulnTotalScore() {
    return vulnTotalScore;
  }


  public void setVulnTotalScore(Float vulnTotalScore) {
    this.vulnTotalScore = vulnTotalScore;
  }



  public ArtifactMetadataAllOf vulnTotalCount(Long vulnTotalCount) {
    
    this.vulnTotalCount = vulnTotalCount;
    return this;
  }

   /**
   * The total number of vulnerabilities of the artifact
   * @return vulnTotalCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "20", value = "The total number of vulnerabilities of the artifact")

  public Long getVulnTotalCount() {
    return vulnTotalCount;
  }


  public void setVulnTotalCount(Long vulnTotalCount) {
    this.vulnTotalCount = vulnTotalCount;
  }



  public ArtifactMetadataAllOf vulnFixableCount(Long vulnFixableCount) {
    
    this.vulnFixableCount = vulnFixableCount;
    return this;
  }

   /**
   * The number of fixable vulnerabilities of the artifact
   * @return vulnFixableCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "10", value = "The number of fixable vulnerabilities of the artifact")

  public Long getVulnFixableCount() {
    return vulnFixableCount;
  }


  public void setVulnFixableCount(Long vulnFixableCount) {
    this.vulnFixableCount = vulnFixableCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ArtifactMetadataAllOf artifactMetadataAllOf = (ArtifactMetadataAllOf) o;
    return Objects.equals(this.lastPushedAt, artifactMetadataAllOf.lastPushedAt) && Objects.equals(this.lastPulledAt, artifactMetadataAllOf.lastPulledAt) && Objects.equals(this.lastScannedAt, artifactMetadataAllOf.lastScannedAt) && Objects.equals(this.pushCount, artifactMetadataAllOf.pushCount) && Objects.equals(this.pullCount, artifactMetadataAllOf.pullCount) && Objects.equals(this.vulnMaxSeverity, artifactMetadataAllOf.vulnMaxSeverity) && Objects.equals(this.vulnTotalScore, artifactMetadataAllOf.vulnTotalScore) && Objects.equals(this.vulnTotalCount, artifactMetadataAllOf.vulnTotalCount) && Objects.equals(this.vulnFixableCount, artifactMetadataAllOf.vulnFixableCount);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ArtifactMetadataAllOf {\n");
    
    sb.append("    lastPushedAt: ").append(toIndentedString(lastPushedAt)).append("\n");

    sb.append("    lastPulledAt: ").append(toIndentedString(lastPulledAt)).append("\n");

    sb.append("    lastScannedAt: ").append(toIndentedString(lastScannedAt)).append("\n");

    sb.append("    pushCount: ").append(toIndentedString(pushCount)).append("\n");

    sb.append("    pullCount: ").append(toIndentedString(pullCount)).append("\n");

    sb.append("    vulnMaxSeverity: ").append(toIndentedString(vulnMaxSeverity)).append("\n");

    sb.append("    vulnTotalScore: ").append(toIndentedString(vulnTotalScore)).append("\n");

    sb.append("    vulnTotalCount: ").append(toIndentedString(vulnTotalCount)).append("\n");

    sb.append("    vulnFixableCount: ").append(toIndentedString(vulnFixableCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

