/*
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.containerregistry.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.containerregistry.model.RegistryFeatures;
import com.ionoscloud.containerregistry.model.WeeklySchedule;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * PatchRegistryInput
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-15T14:36:52.394811Z[Etc/UTC]")

public class PatchRegistryInput {
  
  public static final String SERIALIZED_NAME_GARBAGE_COLLECTION_SCHEDULE = "garbageCollectionSchedule";
  @SerializedName(SERIALIZED_NAME_GARBAGE_COLLECTION_SCHEDULE)
  private WeeklySchedule garbageCollectionSchedule;


  public static final String SERIALIZED_NAME_FEATURES = "features";
  @SerializedName(SERIALIZED_NAME_FEATURES)
  private RegistryFeatures features;

  

  public PatchRegistryInput garbageCollectionSchedule(WeeklySchedule garbageCollectionSchedule) {
    
    this.garbageCollectionSchedule = garbageCollectionSchedule;
    return this;
  }

   /**
   * Get garbageCollectionSchedule
   * @return garbageCollectionSchedule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public WeeklySchedule getGarbageCollectionSchedule() {
    return garbageCollectionSchedule;
  }


  public void setGarbageCollectionSchedule(WeeklySchedule garbageCollectionSchedule) {
    this.garbageCollectionSchedule = garbageCollectionSchedule;
  }



  public PatchRegistryInput features(RegistryFeatures features) {
    
    this.features = features;
    return this;
  }

   /**
   * Get features
   * @return features
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RegistryFeatures getFeatures() {
    return features;
  }


  public void setFeatures(RegistryFeatures features) {
    this.features = features;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PatchRegistryInput patchRegistryInput = (PatchRegistryInput) o;
    return Objects.equals(this.garbageCollectionSchedule, patchRegistryInput.garbageCollectionSchedule) && Objects.equals(this.features, patchRegistryInput.features);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PatchRegistryInput {\n");
    
    sb.append("    garbageCollectionSchedule: ").append(toIndentedString(garbageCollectionSchedule)).append("\n");

    sb.append("    features: ").append(toIndentedString(features)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

