/*
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.containerregistry.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Purl
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-15T14:36:52.394811Z[Etc/UTC]")

public class Purl {
  
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;


  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  

  public Purl type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * The affected package type
   * @return type
  **/
  @ApiModelProperty(example = "maven", required = true, value = "The affected package type")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }



  public Purl name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * The affected package name
   * @return name
  **/
  @ApiModelProperty(example = "org.apache.commons:commons-lang3", required = true, value = "The affected package name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }



  public Purl version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * The affected package version
   * @return version
  **/
  @ApiModelProperty(example = "3.8.1", required = true, value = "The affected package version")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Purl purl = (Purl) o;
    return Objects.equals(this.type, purl.type) && Objects.equals(this.name, purl.name) && Objects.equals(this.version, purl.version);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Purl {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");

    sb.append("    name: ").append(toIndentedString(name)).append("\n");

    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

