/*
 * Container Registry service
 * ## Overview Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls. ## Changelog ### 1.1.0  - Added new endpoints for Repositories  - Added new endpoints for Artifacts  - Added new endpoints for Vulnerabilities  - Added registry vulnerabilityScanning feature 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.containerregistry.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;

/**
 * RepositoryMetadataAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-12-15T14:36:52.394811Z[Etc/UTC]")

public class RepositoryMetadataAllOf {
  
  public static final String SERIALIZED_NAME_ARTIFACT_COUNT = "artifactCount";
  @SerializedName(SERIALIZED_NAME_ARTIFACT_COUNT)
  private Long artifactCount;


  public static final String SERIALIZED_NAME_PULL_COUNT = "pullCount";
  @SerializedName(SERIALIZED_NAME_PULL_COUNT)
  private Long pullCount;


  public static final String SERIALIZED_NAME_PUSH_COUNT = "pushCount";
  @SerializedName(SERIALIZED_NAME_PUSH_COUNT)
  private Long pushCount;


  public static final String SERIALIZED_NAME_LAST_PULLED_AT = "lastPulledAt";
  @SerializedName(SERIALIZED_NAME_LAST_PULLED_AT)
  private OffsetDateTime lastPulledAt;


  public static final String SERIALIZED_NAME_LAST_PUSHED_AT = "lastPushedAt";
  @SerializedName(SERIALIZED_NAME_LAST_PUSHED_AT)
  private OffsetDateTime lastPushedAt;


  public static final String SERIALIZED_NAME_LAST_SEVERITY = "lastSeverity";
  @SerializedName(SERIALIZED_NAME_LAST_SEVERITY)
  private String lastSeverity;

  

  public RepositoryMetadataAllOf artifactCount(Long artifactCount) {
    
    this.artifactCount = artifactCount;
    return this;
  }

   /**
   * Get artifactCount
   * @return artifactCount
  **/
  @ApiModelProperty(example = "125", required = true, value = "")

  public Long getArtifactCount() {
    return artifactCount;
  }


  public void setArtifactCount(Long artifactCount) {
    this.artifactCount = artifactCount;
  }



  public RepositoryMetadataAllOf pullCount(Long pullCount) {
    
    this.pullCount = pullCount;
    return this;
  }

   /**
   * Get pullCount
   * @return pullCount
  **/
  @ApiModelProperty(example = "4200", required = true, value = "")

  public Long getPullCount() {
    return pullCount;
  }


  public void setPullCount(Long pullCount) {
    this.pullCount = pullCount;
  }



  public RepositoryMetadataAllOf pushCount(Long pushCount) {
    
    this.pushCount = pushCount;
    return this;
  }

   /**
   * Get pushCount
   * @return pushCount
  **/
  @ApiModelProperty(example = "200", required = true, value = "")

  public Long getPushCount() {
    return pushCount;
  }


  public void setPushCount(Long pushCount) {
    this.pushCount = pushCount;
  }



  public RepositoryMetadataAllOf lastPulledAt(OffsetDateTime lastPulledAt) {
    
    this.lastPulledAt = lastPulledAt;
    return this;
  }

   /**
   * Get lastPulledAt
   * @return lastPulledAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getLastPulledAt() {
    return lastPulledAt;
  }


  public void setLastPulledAt(OffsetDateTime lastPulledAt) {
    this.lastPulledAt = lastPulledAt;
  }



  public RepositoryMetadataAllOf lastPushedAt(OffsetDateTime lastPushedAt) {
    
    this.lastPushedAt = lastPushedAt;
    return this;
  }

   /**
   * Get lastPushedAt
   * @return lastPushedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getLastPushedAt() {
    return lastPushedAt;
  }


  public void setLastPushedAt(OffsetDateTime lastPushedAt) {
    this.lastPushedAt = lastPushedAt;
  }



  public RepositoryMetadataAllOf lastSeverity(String lastSeverity) {
    
    this.lastSeverity = lastSeverity;
    return this;
  }

   /**
   * The maximum vulnerability severity of the artifact last pushed in the repository, if any
   * @return lastSeverity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The maximum vulnerability severity of the artifact last pushed in the repository, if any")

  public String getLastSeverity() {
    return lastSeverity;
  }


  public void setLastSeverity(String lastSeverity) {
    this.lastSeverity = lastSeverity;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RepositoryMetadataAllOf repositoryMetadataAllOf = (RepositoryMetadataAllOf) o;
    return Objects.equals(this.artifactCount, repositoryMetadataAllOf.artifactCount) && Objects.equals(this.pullCount, repositoryMetadataAllOf.pullCount) && Objects.equals(this.pushCount, repositoryMetadataAllOf.pushCount) && Objects.equals(this.lastPulledAt, repositoryMetadataAllOf.lastPulledAt) && Objects.equals(this.lastPushedAt, repositoryMetadataAllOf.lastPushedAt) && Objects.equals(this.lastSeverity, repositoryMetadataAllOf.lastSeverity);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RepositoryMetadataAllOf {\n");
    
    sb.append("    artifactCount: ").append(toIndentedString(artifactCount)).append("\n");

    sb.append("    pullCount: ").append(toIndentedString(pullCount)).append("\n");

    sb.append("    pushCount: ").append(toIndentedString(pushCount)).append("\n");

    sb.append("    lastPulledAt: ").append(toIndentedString(lastPulledAt)).append("\n");

    sb.append("    lastPushedAt: ").append(toIndentedString(lastPushedAt)).append("\n");

    sb.append("    lastSeverity: ").append(toIndentedString(lastSeverity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

