/*
 * Container Registry service
 * Container Registry service enables IONOS clients to manage docker and OCI compliant registries for use by their managed Kubernetes clusters. Use a Container Registry to ensure you have a privately accessed registry to efficiently support image pulls.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@cloud.ionos.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.containerregistry.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.containerregistry.model.Day;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * WeeklySchedule
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-21T15:19:22.180Z[Etc/UTC]")

public class WeeklySchedule {
  public static final String SERIALIZED_NAME_DAYS = "days";
  @SerializedName(SERIALIZED_NAME_DAYS)
  private List<Day> days = new ArrayList<Day>();

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private String time;


  public WeeklySchedule days(List<Day> days) {
    
    this.days = days;
    return this;
  }

  public WeeklySchedule addDaysItem(Day daysItem) {
    this.days.add(daysItem);
    return this;
  }

   /**
   * Get days
   * @return days
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(required = true, value = "")

  public List<Day> getDays() {
    return days;
  }


  public void setDays(List<Day> days) {
    this.days = days;
  }


  public WeeklySchedule time(String time) {
    
    this.time = time;
    return this;
  }

   /**
   * UTC time of day e.g. 01:00:00 - as defined by partial-time - RFC3339
   * @return time
  **/
  @ApiModelProperty(example = "01:23:00+00:00", required = true, value = "UTC time of day e.g. 01:00:00 - as defined by partial-time - RFC3339")

  public String getTime() {
    return time;
  }


  public void setTime(String time) {
    this.time = time;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WeeklySchedule weeklySchedule = (WeeklySchedule) o;
    return Objects.equals(this.days, weeklySchedule.days) && Objects.equals(this.time, weeklySchedule.time);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WeeklySchedule {\n");
    sb.append("    days: ").append(toIndentedString(days)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

